POST http://localhost:5000/bonds
   Content-Type: application/json

   {
        "holdingName": "New Bond",
       "dateOfPurchase": "2023-01-03",
       "priceAtPurchase":9.99,
       "qty": 10,
       "currentPrice": 10.99,
       "parValue": 10.99,
       "maturityDate": "2026-01-01",
       "coupon": 0.7,
       "discountRate": 0.05

       
   }
   