POST http://localhost:5000/cash
   Content-Type: application/json

   {
       "id": "22", 
        "holdingName": "New Cash",
       "dateOfPurchase": "2023-01-04",
       "exchAtPurchase":9.99,
       "qty": 10,
       "exchCurrent": 10.99,
       "currentValue": 10

       
   }